public class ConstantUTIL {

     public static string method='POST';
     public static string methodget='GET';
     public static string content='Content-type';
     public static string contentType='application/json';
     public static string auth='Authorization';
     public static string authprefix='Bearer ';
     public static string lne='Line';
     public static string detail='DetailType';
     public static string sales='SalesItemLineDetail';
    
}