global class DailyLeadProcessor implements Schedulable{
    global void execute(SchedulableContext sc)
    {
   //    List<Lead> lstoflead =[SELECT id from Lead where LeadSource=NULL LIMIT 200];
      // List<Lead> lstofupdated = new List<Lead>();
        
     
      //     for(Lead l:lstoflead)
      //     {
      //        l.LeadSource='Dreamforce';
     //         lstofupdated.add(l);
      //     }
           
       //    update lstofupdated;
      
        
    }

}